// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace SimpleBank
{
    public partial class UtilsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UtilsTest))]
[HostType("Moles")]
public void GetMessage376()
{
    string s;
    s = this.GetMessage(false);
    Assert.AreEqual<string>("Just a normal day!", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UtilsTest))]
[HostType("Moles")]
public void GetMessage479()
{
    string s;
    s = this.GetMessage(PexSafeHelpers.ByteToBoolean((byte)2));
    Assert.AreEqual<string>("Happy New Year!", s);
}
    }
}
