// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using SimpleBank.Domain;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace SimpleBank
{
    public partial class AccountServiceTest
    {
[TestMethod]
[PexGeneratedBy(typeof(AccountServiceTest))]
public void ComputeInterest268()
{
    Account account;
    decimal d;
    account = new Account();
    account.Id = 0;
    account.Balance = default(decimal);
    account.AutorizeOverdraft = false;
    d = this.ComputeInterest(account, 1, 1);
    Assert.AreEqual<decimal>(833333333333333e-13M, d);
}
[TestMethod]
[PexGeneratedBy(typeof(AccountServiceTest))]
[ExpectedException(typeof(AccountServiceException))]
public void ComputeInterestThrowsAccountServiceException406()
{
    decimal d;
    d = this.ComputeInterest((Account)null, 1, 1);
}
    }
}
