// <copyright file="UtilsTest.SomeDumpMethod.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace SimpleBank
{
    public partial class UtilsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UtilsTest))]
public void SomeDumpMethod786()
{
    string s;
    s = this.SomeDumpMethod(0, 0);
    Assert.AreEqual<string>("output3", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UtilsTest))]
public void SomeDumpMethod780()
{
    string s;
    s = this.SomeDumpMethod(1, 0);
    Assert.AreEqual<string>("output2", s);
}
[TestMethod]
[PexGeneratedBy(typeof(UtilsTest))]
public void SomeDumpMethod55()
{
    string s;
    s = this.SomeDumpMethod(13, 12);
    Assert.AreEqual<string>("output1", s);
}
    }
}
